// <auto-generated />
using System;
using GearCore.Monolith.Infra.Data.Commons.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearCore.Monolith.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearCore.Monolith.Core.ProductCore.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COL_BRAND")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATED_AT")
                        .HasColumnOrder(6);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("COL_DESCRIPTION")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("COL_IS_ACTIVE")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("COL_NAME")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_PRICE")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_UPDATED_AT")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUCT", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.Stock", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COL_FK_PRODUCTID")
                        .HasColumnOrder(0);

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_CURRENT_QUANTITY")
                        .HasColumnOrder(1);

                    b.HasKey("ProductId");

                    b.ToTable("TB_STOCK", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.StockMoviments", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_MOVEMENT_DATE")
                        .HasColumnOrder(5);

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_MOVEMENT_TYPE")
                        .HasColumnOrder(6);

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_NEW_QUANTITY")
                        .HasColumnOrder(4);

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_OBSERVATION")
                        .HasColumnOrder(8);

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_ORIGIN")
                        .HasColumnOrder(7);

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_PREVIOUS_QUANTITY")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COL_FK_PRODUCTID")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_QUANTITY")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("TB_STOCK_MOVIMENTS", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.Stock", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.ProductCore.Entities.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("GearCore.Monolith.Core.StockCore.Entities.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.StockMoviments", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.ProductCore.Entities.Product", "Product")
                        .WithMany("Moviments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.ProductCore.Entities.Product", b =>
                {
                    b.Navigation("Moviments");

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
