// <auto-generated />
using System;
using GearCore.Monolith.Infra.Data.Commons.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearCore.Monolith.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearCore.Monolith.Core.ProductCore.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COL_BRAND")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATE_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("COL_DESCRIPTION")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("COL_IS_ACTIVE")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("COL_NAME")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_PRICE")
                        .HasColumnOrder(3);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("FK_TENANT_ID")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name", "Brand")
                        .IsUnique()
                        .HasFilter("[COL_BRAND] IS NOT NULL");

                    b.ToTable("TB_PRODUCT", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.SalesCore.Entities.SaleItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_PRODUCT_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_PRODUCT_NAME")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_QUANTITY")
                        .HasColumnOrder(5);

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_SALE_ID")
                        .HasColumnOrder(1);

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_TOTAL_PRICE")
                        .HasColumnOrder(6);

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_UNIT_PRICE")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("TB_SALE_ITEM", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.SalesCore.Entities.Sales", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATE_AT");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_DISCOUNT_AMOUNT")
                        .HasColumnOrder(4);

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_FINAL_AMOUNT")
                        .HasColumnOrder(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_STATUS")
                        .HasColumnOrder(6);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("FK_TENANT_ID")
                        .HasColumnOrder(1);

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COL_TOTAL_AMOUNT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_UPDATE_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_USER_ID")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_SALES", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.Stock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("COL_ACTIVE")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATE_AT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_PRODUCT_ID")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_QUANTITY")
                        .HasColumnOrder(4);

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_RESERVED_QUANTITY")
                        .HasColumnOrder(5);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("FK_TENANT_ID")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.ToTable("TB_STOCK", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.StockMoviments", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATE_AT")
                        .HasColumnOrder(6);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("COL_QUANTITY")
                        .HasColumnOrder(3);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COL_REASON")
                        .HasColumnOrder(4);

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("COL_REFERENCE_ID")
                        .HasColumnOrder(5);

                    b.Property<string>("StocksId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_STOCK_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_TYPE")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("StocksId");

                    b.ToTable("TB_STOCK_MOVIMENTS", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.TenantCore.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("COL_IS_ACTIVE")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_NAME")
                        .HasColumnOrder(1);

                    b.Property<string>("Subdomain")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_SUBDOMAIN")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("TB_TENANT", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.TenantCore.Entities.TenantUser", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("COL_TENANT_ID");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_USER_ID");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime2")
                        .HasColumnName("COL_CREATED_BY");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("COL_IS_ACTIVE");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COL_ROLE");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_TENANT_USER", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_DESCRIPTION")
                        .HasColumnOrder(2);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COL_NAME")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("TB_ROLE", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("COL_ACCESS_FAILED_COUNT")
                        .HasColumnOrder(11);

                    b.Property<string>("CompleteName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("COL_COMPLETE_NAME")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_EMAIL")
                        .HasColumnOrder(6);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("COL_EMAIL_CONFIRMED")
                        .HasColumnOrder(8);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_FIRST_NAME")
                        .HasColumnOrder(1);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_LAST_NAME")
                        .HasColumnOrder(3);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_NORMALIZED_EMAIL")
                        .HasColumnOrder(7);

                    b.Property<string>("NormalizedFirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_NORMALIZED_FIRSTNAME")
                        .HasColumnOrder(2);

                    b.Property<string>("NormalizedLastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("COL_NORMALIZED_LASTNAME")
                        .HasColumnOrder(4);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("COL_PASSWORD_HASH")
                        .HasColumnOrder(12);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("COL_PHONE_NUMBER")
                        .HasColumnOrder(9);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("COL_PHONE_NUMBER_CONFIRMED")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("CompleteName");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedFirstName");

                    b.HasIndex("NormalizedLastName");

                    b.ToTable("TB_USERS", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.UserRoles", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_USER_ID");

                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("COL_ROLE_ID");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("TB_USER_ROLE", (string)null);
                });

            modelBuilder.Entity("GearCore.Monolith.Core.ProductCore.Entities.Product", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.TenantCore.Entities.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.SalesCore.Entities.SaleItem", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.ProductCore.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearCore.Monolith.Core.SalesCore.Entities.Sales", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.SalesCore.Entities.Sales", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.TenantCore.Entities.Tenant", "Tenant")
                        .WithMany("Sales")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearCore.Monolith.Core.UserCore.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.Stock", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.ProductCore.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearCore.Monolith.Core.TenantCore.Entities.Tenant", "Tenant")
                        .WithMany("Stocks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.StockMoviments", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.StockCore.Entities.Stock", "Stocks")
                        .WithMany("StockMoviments")
                        .HasForeignKey("StocksId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.TenantCore.Entities.TenantUser", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.TenantCore.Entities.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearCore.Monolith.Core.UserCore.Entities.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.UserRoles", b =>
                {
                    b.HasOne("GearCore.Monolith.Core.UserCore.Entities.Roles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearCore.Monolith.Core.UserCore.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.ProductCore.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.SalesCore.Entities.Sales", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.StockCore.Entities.Stock", b =>
                {
                    b.Navigation("StockMoviments");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.TenantCore.Entities.Tenant", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sales");

                    b.Navigation("Stocks");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GearCore.Monolith.Core.UserCore.Entities.User", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
